import 'reflect-metadata';
import './styles/tokens.css';
import './styles/global.css';
import './styles/dialog-templates.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import './router.js';
import './ui/button/aa-button.js';
import './ui/badge/aa-badge.js';
import './ui/card/aa-card.js';
import './ui/empty-state/aa-empty-state.js';
import './ui/error-state/aa-error-state.js';
import './ui/form-field/aa-form-field.js';
import './ui/page-header/aa-page-header.js';
import './ui/stat/aa-stat.js';
import './components/navigationbar-cmp/navigationbar-cmp.js';
import './components/pages/index-page/index-page.js';
import './components/pages/changelog-page/changelog-page.js';
import './components/pages/users-page/users-page.js';
import './components/pages/user-page/user-page.js';
import './components/pages/season-page/season-page.js';
import './components/pages/seasons-page/seasons-page.js';
import './components/pages/sessions-page/sessions-page.js';
import './components/pages/spectate-game-page/spectate-game-page.js';
import './components/aa-notification-cmp/aa-notification-cmp.js';
import './components/aa-notification-container-cmp/aa-notification-container-cmp.js';
import './components/aa-dart-throw-cmp/aa-dart-throw-cmp.js';
import './components/aa-combobox-cmp/aa-combobox-cmp.js';
import './components/aa-match-snapshot-chart/aa-match-snapshot-chart.js';
import './components/aa-heatmap-chart/aa-heatmap-chart.js';
import './components/aa-finish-count-chart/aa-finish-count-chart.js';
import './components/aa-info-tooltip/aa-info-tooltip.js';
import './components/aa-mmr-configuration-editor/aa-mmr-configuration-editor.js';
import './components/aa-user-picker/aa-user-picker.js';
import './components/aa-dialog/aa-dialog.js';
import './components/rank-display/aa-rank-display.js';
import './components/player-chip/aa-player-chip.js';
import './getAbsoluteBase.js';

import hljs from 'highlight.js/lib/core';
import csharp from 'highlight.js/lib/languages/csharp';
import { container } from 'tsyringe';

import { achievementService } from './services/achievementService.js';
import { CacheService } from './services/cacheService.js';
import { DataService } from './services/dataService.js';
import { DialogService } from './services/dialogService.js';
import { GameService } from './services/gameService.js';
import { NotificationService } from './services/notificationService.js';
import { RuleService } from './services/ruleService.js';
import { SeasonService } from './services/seasonService.js';
import { signalRService } from './services/signalRService.js';
import { UserService } from './services/userService.js';

container.register(DataService,         { useClass: DataService });
container.register(NotificationService, { useClass: NotificationService });
container.register(DialogService,       { useClass: DialogService });
container.register(SeasonService,       { useClass: SeasonService });
container.register(UserService,         { useClass: UserService });
container.register(CacheService,        { useClass: CacheService });
container.register(GameService,         { useClass: GameService });
container.register(RuleService,         { useClass: RuleService });
container.register(signalRService,      { useClass: signalRService });
container.register(achievementService,      { useClass: achievementService });


hljs.registerLanguage('csharp', csharp);
